Feature: testing
meme-es/tic-tac-toe pull request #7
Opened 2020-04-10 19:22 UTC by meme-es

### Testing
This pull request delivers test specs over the public methods of the project:

Public methods of UserInterface:
* #play

Public methods of Player:
* #name
* #character
* #score

Public methods of Game
* #move
* #free?
* #board
* #ended

2020-04-11 10:19 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello, 
You have written an amazing test, simply to read. Thank for that.
However, there are some changes to do

1. I run the test and I got this error
```ruby
$ rspec spec/
Please introduce the first player's name: F..............

Failures:

  1) UserInterface#play when the method is called returns nil allways
     Failure/Error: new_name = gets.chomp
     
     Errno::EISDIR:
       Is a directory @ io_fillbuf - fd:5 spec/
     # ./lib/userinterface.rb:42:in `gets'
     # ./lib/userinterface.rb:42:in `gets'
     # ./lib/userinterface.rb:42:in `block in choose_name'
     # ./lib/userinterface.rb:40:in `loop'
     # ./lib/userinterface.rb:40:in `choose_name'
     # ./lib/userinterface.rb:33:in `new_player'
     # ./lib/userinterface.rb:6:in `play'
     # ./spec/tic_tac_toe_spec.rb:13:in `block (4 levels) in <top (required)>'

Finished in 0.0074 seconds (files took 0.08168 seconds to load)
15 examples, 1 failure

Failed examples:

rspec ./spec/tic_tac_toe_spec.rb:12 # UserInterface#play when the method is called returns nil allways
```
You can write test for **I/O method**, that is for `UserInterface#play`.

2. Please, move the test of each class in their own file.

3. Read the comment below.

Kindly make those changes and submit a new code review request.
Thanks

Mael FOSSO

2020-04-11 10:19 UTC, maelfosso commented on spec/tic_tac_toe_spec.rb
> +    end
Testing the `move` method in your situation will result to compare the board content, not the return value
```ruby
game.move(player, 5)
expect(game.board). to be([....])
```

2020-04-11 20:13 UTC, mosesogwo requested changes
**Hi @meme-es, @kbjude :clap:. Good job:+1:, but you haven't effected all the changes requested from the previous review**.
- In testing the **move** method, you should check the status of the board after the move has been made; not just the return value. See the previous reviewer's comment on this.
- In addition to the above, for your player_spec, you should check if the return value is correct and not just the class of the return value. See comments on your spec file below.

_**Kindly make these changes and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-04-11 20:13 UTC, mosesogwo commented on spec/player_spec.rb
> +        expect(player.name).to be_an_instance_of(String)
You should add another test to check if the string returned is 'Manuel'

2020-04-11 20:13 UTC, mosesogwo commented on spec/player_spec.rb
> +        expect(player.character).to be_an_instance_of(String)
You should add a test to check that the string returned is exactly the player's character

2020-04-11 20:13 UTC, mosesogwo commented on spec/game_spec.rb
> +        expect(game.board).to be_an_instance_of(String)
You should add test to check that the string returned correctly represents the state of the board.

2020-04-12 14:48 UTC, maelfosso approved these changes
# Congratulations :clap: 

You can merge it :+1: 
Good luck with the next :handshake: 

Mael FOSSO

2020-04-12 15:05 UTC, meme-es commented
Thank you @maelfosso & @mosesogwo for your help.

2020-04-12 15:54 UTC, merged